theme: jekyll-theme-hacker
show_downloads: false
github:
  is_project_page: false
permalink: README.md
defaults:
  - 
    scope:
      path: "README.md"
    values:
      permalink: "README.md"
plugins:
  - jekyll-readme-index
